import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ekle import ekle
ekle({
 "Bu metin bilgilendirme amaçlıdır; yayına":{"en":"This text is for information purposes; we recommend reviewing it with your legal adviser before publishing.","ka":"ეს ტექსტი საინფორმაციო ხასიათისაა; გამოქვეყნებამდე რეკომენდებულია იურისტთან გადამოწმება.","ar":"هذا النص لأغراض إعلامية؛ ويُنصح بمراجعته مع مستشاركم القانوني قبل النشر."},
 "numaralı telefondan bize ulaşabilirsiniz.":{"en":". You can also reach us by phone on this number.","ka":". ასევე შეგიძლიათ დაგვიკავშირდეთ ამ ნომერზე.","ar":". ويمكنكم أيضًا الاتصال بنا على هذا الرقم."},
 "Rızanız":{"en":"Your consent","ka":"თქვენი თანხმობა","ar":"موافقتكم"},
 "Zorunlu çerezler sitenin çalışması":{"en":"Essential cookies are required for the site to work and do not need consent. All other categories are","ka":"აუცილებელი ქუქი-ფაილები საჭიროა საიტის მუშაობისთვის და თანხმობას არ საჭიროებს. ყველა სხვა კატეგორია","ar":"ملفات الارتباط الضرورية لازمة لعمل الموقع ولا تتطلّب موافقة. أما جميع الفئات الأخرى فهي"},
 "varsayılan olarak kapalıdır":{"en":"switched off by default","ka":"ნაგულისხმევად გამორთულია","ar":"مُعطّلة افتراضيًا"},
 "; yalnızca siz izin verdiğinizde":{"en":"; they run only when you allow them. You can change your preference at any time from the","ka":"; ისინი მუშაობს მხოლოდ თქვენი ნებართვით. თქვენი არჩევანი ნებისმიერ დროს შეგიძლიათ შეცვალოთ გვერდის ბოლოს არსებული","ar":"؛ ولا تعمل إلا بموافقتكم. ويمكنكم تغيير تفضيلاتكم في أي وقت من"},
 "bağlantısından değiştirebilir":{"en":"link at the bottom of the page, or withdraw your consent.","ka":"ბმულიდან, ან გამოიხმოთ თანხმობა.","ar":"الرابط أسفل الصفحة، أو سحب موافقتكم."},
 "Kullanılan çerezler":{"en":"Cookies used","ka":"გამოყენებული ქუქი-ფაილები","ar":"ملفات الارتباط المستخدمة"},
 "Ad":{"en":"Name","ka":"სახელი","ar":"الاسم"},
 "Kategori":{"en":"Category","ka":"კატეგორია","ar":"الفئة"},
 "Amaç":{"en":"Purpose","ka":"დანიშნულება","ar":"الغرض"},
 "Süre":{"en":"Duration","ka":"ხანგრძლივობა","ar":"المدة"},
 "Taraf":{"en":"Party","ka":"მხარე","ar":"الجهة"},
 "Zorunlu":{"en":"Essential","ka":"აუცილებელი","ar":"ضروري"},
 "Çerez tercihinizi kaydeder":{"en":"Stores your cookie preference; prevents the banner from reappearing","ka":"ინახავს თქვენს არჩევანს ქუქი-ფაილებზე; ხელს უშლის ბანერის განმეორებით გამოჩენას","ar":"يحفظ تفضيلكم بشأن ملفات الارتباط ويمنع ظهور الشريط مجددًا"},
 "Kalıcı (siz silene kadar)":{"en":"Persistent (until you delete it)","ka":"მუდმივი (სანამ თავად არ წაშლით)","ar":"دائم (حتى تحذفوه)"},
 "Birinci taraf":{"en":"First party","ka":"პირველი მხარე","ar":"طرف أول"},
 "Tercih":{"en":"Preference","ka":"პარამეტრი","ar":"تفضيل"},
 "Kapattığınız duyuru bandının":{"en":"Keeps the announcement bar you closed from opening again","ka":"არ აჩენს ხელახლა თქვენ მიერ დახურულ საინფორმაციო ზოლს","ar":"يمنع إعادة فتح شريط الإعلان الذي أغلقتموه"},
 "Kalıcı":{"en":"Persistent","ka":"მუდმივი","ar":"دائم"},
 "Açılış duyuru penceresinin":{"en":"Prevents the welcome announcement window from showing again in the same session","ka":"ხელს უშლის მისალმების ფანჯრის განმეორებით ჩვენებას იმავე სესიაზე","ar":"يمنع ظهور نافذة الإعلان الترحيبية مجددًا في الجلسة نفسها"},
 "Oturum süresi":{"en":"Session","ka":"სესიის ხანგრძლივობა","ar":"مدة الجلسة"},
 "Yönetim paneli oturumu":{"en":"Management panel session (authorised staff only)","ka":"მართვის პანელის სესია (მხოლოდ უფლებამოსილი პერსონალი)","ar":"جلسة لوحة الإدارة (للموظفين المخوّلين فقط)"},
 "Google Haritalar gömme":{"en":"Google Maps embed","ka":"Google Maps ჩაშენება","ar":"خريطة جوجل المدمجة"},
 "Sayfa altındaki harita.":{"en":"The map at the bottom of the page.","ka":"რუკა გვერდის ბოლოს.","ar":"الخريطة في أسفل الصفحة."},
 "Yalnızca tercih çerezlerine izin":{"en":"It loads only if you have allowed preference cookies","ka":"ის იტვირთება მხოლოდ იმ შემთხვევაში, თუ დაუშვით პარამეტრების ქუქი-ფაილები","ar":"تُحمَّل فقط إذا سمحتم بملفات ارتباط التفضيلات"},
 "yüklenir; izin yoksa":{"en":"; without consent a map image requiring no external connection is shown instead. When loaded, Google may set cookies.","ka":"; თანხმობის გარეშე ნაცვლად ჩვენდება რუკის სურათი, რომელიც გარე კავშირს არ საჭიროებს. ჩატვირთვისას Google-მა შესაძლოა დააყენოს ქუქი-ფაილები.","ar":"؛ وبدون موافقة تُعرض بدلاً منها صورة خريطة لا تتطلّب أي اتصال خارجي. وعند تحميلها قد تضع جوجل ملفات ارتباط."},
 "Google'ın politikasına tabi":{"en":"Subject to Google's policy","ka":"ექვემდებარება Google-ის პოლიტიკას","ar":"يخضع لسياسة جوجل"},
 "Üçüncü taraf (Google)":{"en":"Third party (Google)","ka":"მესამე მხარე (Google)","ar":"طرف ثالث (جوجل)"},
 "Yönetim panelinde düzenlenen":{"en":"Temporary record of site content edited in the management panel (authorised staff only)","ka":"მართვის პანელში რედაქტირებული შიგთავსის დროებითი ჩანაწერი (მხოლოდ უფლებამოსილი პერსონალი)","ar":"سجلّ مؤقت لمحتوى الموقع المحرَّر في لوحة الإدارة (للموظفين المخوّلين فقط)"},
 "Bu sitede":{"en":"This site","ka":"ამ საიტზე","ar":"في هذا الموقع"},
 "üçüncü taraf ölçümleme":{"en":"does not use third-party analytics or advertising cookies","ka":"არ გამოიყენება მესამე მხარის ანალიტიკური ან სარეკლამო ქუქი-ფაილები","ar":"لا تُستخدم ملفات ارتباط تحليلية أو إعلانية من طرف ثالث"},
 ". Tek üçüncü taraf içerik":{"en":". The only third-party content is the Google Maps embed at the bottom of the page, and it loads only if you have allowed preference cookies.","ka":". ერთადერთი მესამე მხარის შიგთავსი არის Google Maps-ის ჩაშენებული რუკა გვერდის ბოლოს და ის იტვირთება მხოლოდ პარამეტრების ქუქი-ფაილების დაშვების შემთხვევაში.","ar":". والمحتوى الوحيد من طرف ثالث هو خريطة جوجل المدمجة أسفل الصفحة، ولا تُحمَّل إلا إذا سمحتم بملفات ارتباط التفضيلات."},
 "Tarayıcı ayarları":{"en":"Browser settings","ka":"ბრაუზერის პარამეტრები","ar":"إعدادات المتصفح"},
 "Çerezleri tarayıcı ayarlarınızdan":{"en":"You can also delete or block cookies from your browser settings. If you block essential cookies, parts of the site may not work.","ka":"ქუქი-ფაილების წაშლა ან დაბლოკვა ბრაუზერის პარამეტრებიდანაც შეგიძლიათ. აუცილებელი ქუქი-ფაილების დაბლოკვის შემთხვევაში საიტის ნაწილები შესაძლოა არ იმუშაოს.","ar":"يمكنكم أيضًا حذف ملفات الارتباط أو حظرها من إعدادات متصفحكم. وإذا حظرتم الملفات الضرورية فقد لا تعمل بعض أجزاء الموقع."},
 "Çerez kullanımıyla ilgili sorularınız":{"en":"For questions about our use of cookies you can write to","ka":"ქუქი-ფაილების გამოყენებასთან დაკავშირებული კითხვებისთვის მოგვწერეთ","ar":"لأي أسئلة بشأن استخدامنا لملفات الارتباط يمكنكم المراسلة على"},
 "adresine yazabilir ya da":{"en":"or reach us by phone on","ka":"ან დაგვიკავშირდით ტელეფონით","ar":"أو الاتصال بنا على الرقم"},
 "numaralı telefondan bize ulaşabilirsiniz. Kişisel":{"en":". For your rights regarding personal data you can see our","ka":". პერსონალურ მონაცემებთან დაკავშირებული უფლებებისთვის იხილეთ ჩვენი","ar":". ولمعرفة حقوقكم بشأن البيانات الشخصية يمكنكم مراجعة"},
 "Gizlilik Politikası ve KVKK Aydınlatma Metni":{"en":"Privacy Policy and Data Protection Notice","ka":"კონფიდენციალურობის პოლიტიკა და მონაცემთა დაცვის შეტყობინება","ar":"سياسة الخصوصية وإشعار حماية البيانات"},
 "sayfamıza bakabilirsiniz.":{"en":"page.","ka":"გვერდი.","ar":"صفحتنا."},
 "Not:":{"en":"Note:","ka":"შენიშვნა:","ar":"ملاحظة:"},
 "Bu metin bilgilendirme amaçlıdır. Yayına":{"en":"This text is for information purposes. Before publishing, fill in the fields marked in square brackets and have the text reviewed by a legal adviser.","ka":"ეს ტექსტი საინფორმაციო ხასიათისაა. გამოქვეყნებამდე შეავსეთ კვადრატულ ფრჩხილებში მონიშნული ველები და ტექსტი გადაამოწმებინეთ იურისტს.","ar":"هذا النص لأغراض إعلامية. قبل النشر، املأوا الحقول المحدّدة بين قوسين معقوفين واعرضوا النص على مستشار قانوني."},
 "Park Ardeşen AVM internet sitesinin kullanım":{"en":"Terms of use, content accuracy and intellectual property information for the Park Ardeşen AVM website.","ka":"Park Ardeşen AVM-ის ვებგვერდის გამოყენების პირობები, შიგთავსის სიზუსტე და ინტელექტუალური საკუთრების ინფორმაცია.","ar":"شروط استخدام موقع بارك أرديشن مول ودقة المحتوى ومعلومات الملكية الفكرية."},
 "İletişim — Park Ardeşen AVM":{"en":"Contact — Park Ardeşen AVM | Ardeşen, Rize","ka":"კონტაქტი — Park Ardeşen AVM | არდეშენი, რიზე","ar":"اتصل بنا — بارك أرديشن مول | أرديشن، ريزة"},
 "Adres":{"en":"Address","ka":"მისამართი","ar":"العنوان"},
 "Cumhuriyet Mah. Sultan Alparslan Cad. No: 2/1":{"en":"Cumhuriyet Mah. Sultan Alparslan Cad. No: 2/1","ka":"Cumhuriyet Mah. Sultan Alparslan Cad. No: 2/1","ar":"حي جمهوريت، شارع سلطان ألب أرسلان، رقم 2/1"},
 "Telefon":{"en":"Phone","ka":"ტელეფონი","ar":"الهاتف"},
 "E-posta":{"en":"Email","ka":"ელფოსტა","ar":"البريد الإلكتروني"},
})
