import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ekle import ekle
K = lambda t: {"en": t, "ka": t, "ar": t}      # değişmeden kalan teknik ad
ekle({
 "Her ayın ilk haftası Park Ardeşen AVM'de":{"en":"The first week of every month at Park Ardeşen AVM","ka":"ყოველი თვის პირველ კვირას Park Ardeşen AVM-ში","ar":"في الأسبوع الأول من كل شهر في بارك أرديشن مول"},
 "pa-cerez-izni": K("pa-cerez-izni"),
 "pa-serit-kapali": K("pa-serit-kapali"),
 "pa-pencere": K("pa-pencere"),
 "pa-panel, pa-panel-s": K("pa-panel, pa-panel-s"),
 "pa-veri": K("pa-veri"),
 "Çalışma saatleri":{"en":"Opening hours","ka":"სამუშაო საათები","ar":"ساعات العمل"},
 "Pazartesi – Pazar":{"en":"Monday – Sunday","ka":"ორშაბათი – კვირა","ar":"الاثنين – الأحد"},
 "Resmî tatillerde ve özel günlerde":{"en":"Hours may change on public holidays and special days.","ka":"საათები შესაძლოა შეიცვალოს ოფიციალურ დღესასწაულებსა და განსაკუთრებულ დღეებში.","ar":"قد تتغيّر الساعات في العطل الرسمية والمناسبات الخاصة."},
 "İşletme bilgileri":{"en":"Company details","ka":"კომპანიის მონაცემები","ar":"بيانات المنشأة"},
 "Ticari unvan":{"en":"Registered trade name","ka":"სავაჭრო დასახელება","ar":"الاسم التجاري المسجّل"},
 "[DOLDURULACAK: işletmenin resmî ticari unvanı]":{"en":"[TO BE COMPLETED: the company's registered trade name]","ka":"[შესავსებია: კომპანიის ოფიციალური სავაჭრო დასახელება]","ar":"[يُستكمل: الاسم التجاري الرسمي للمنشأة]"},
 "Cumhuriyet Mah. Sultan Alparslan Cad. No: 2/1, 53400":{"en":"Cumhuriyet Mah. Sultan Alparslan Cad. No: 2/1, 53400 Ardeşen / Rize","ka":"Cumhuriyet Mah. Sultan Alparslan Cad. No: 2/1, 53400 არდეშენი / რიზე","ar":"حي جمهوريت، شارع سلطان ألب أرسلان، رقم 2/1، 53400 أرديشن / ريزة"},
 "Vergi dairesi / numarası":{"en":"Tax office / number","ka":"საგადასახადო ორგანო / ნომერი","ar":"مكتب الضرائب / الرقم"},
 "[DOLDURULACAK]":{"en":"[TO BE COMPLETED]","ka":"[შესავსებია]","ar":"[يُستكمل]"},
 "MERSİS numarası":{"en":"MERSİS number","ka":"MERSİS ნომერი","ar":"رقم MERSİS"},
 "KEP adresi":{"en":"Registered e-mail (KEP) address","ka":"რეგისტრირებული ელფოსტის (KEP) მისამართი","ar":"عنوان البريد الإلكتروني المسجّل (KEP)"},
 "Bize yazın":{"en":"Write to us","ka":"მოგვწერეთ","ar":"راسلونا"},
 "Formu doldurduğunuzda":{"en":"When you fill in the form, your message opens ready in your email application; all you need to do is press send.","ka":"ფორმის შევსების შემდეგ თქვენი შეტყობინება მზა სახით იხსნება ელფოსტის აპლიკაციაში; საჭიროა მხოლოდ გაგზავნის დაჭერა.","ar":"عند تعبئة النموذج، تُفتح رسالتكم جاهزة في تطبيق البريد لديكم؛ ولا يتبقّى سوى الضغط على إرسال."},
 "adresine de yazabilirsiniz.":{"en":"You can also write to us at this address.","ka":"ასევე შეგიძლიათ მოგვწეროთ ამ მისამართზე.","ar":"ويمكنكم أيضًا مراسلتنا على هذا العنوان."},
 "Ad Soyad":{"en":"Full name","ka":"სახელი და გვარი","ar":"الاسم الكامل"},
 "Konu":{"en":"Subject","ka":"თემა","ar":"الموضوع"},
 "Genel bilgi":{"en":"General enquiry","ka":"ზოგადი ინფორმაცია","ar":"استفسار عام"},
 "Mağaza kiralama":{"en":"Store leasing","ka":"მაღაზიის იჯარა","ar":"تأجير متجر"},
 "Kariyer / iş başvurusu":{"en":"Careers / job application","ka":"კარიერა / განაცხადი","ar":"وظائف / طلب توظيف"},
 "Kayıp eşya":{"en":"Lost property","ka":"დაკარგული ნივთი","ar":"مفقودات"},
 "Öneri ve şikâyet":{"en":"Suggestions and complaints","ka":"წინადადებები და საჩივრები","ar":"اقتراحات وشكاوى"},
 "Basın":{"en":"Press","ka":"პრესა","ar":"الصحافة"},
 "Mesajınız":{"en":"Your message","ka":"თქვენი შეტყობინება","ar":"رسالتكم"},
 "ni okudum; mesajımı yanıtlayabilmeniz":{"en":"I have read it; I consent to the processing of my personal data so that you can reply to my message.","ka":"წავიკითხე; თანახმა ვარ ჩემი პერსონალური მონაცემების დამუშავებაზე, რათა შეძლოთ ჩემს შეტყობინებაზე პასუხის გაცემა.","ar":"لقد اطّلعت عليها؛ وأوافق على معالجة بياناتي الشخصية لتتمكّنوا من الردّ على رسالتي."},
 "Mesajı hazırla":{"en":"Prepare message","ka":"შეტყობინების მომზადება","ar":"تجهيز الرسالة"},
 "Bize doğrudan ulaşın":{"en":"Contact us directly","ka":"დაგვიკავშირდით პირდაპირ","ar":"تواصلوا معنا مباشرة"},
 "Park Ardeşen AVM adres, telefon ve çalışma":{"en":"Park Ardeşen AVM address, phone and opening hours. Cumhuriyet Mah. Sultan Alparslan Cad. No: 2/1, Ardeşen / Rize.","ka":"Park Ardeşen AVM-ის მისამართი, ტელეფონი და სამუშაო საათები. Cumhuriyet Mah. Sultan Alparslan Cad. No: 2/1, არდეშენი / რიზე.","ar":"عنوان بارك أرديشن مول وهاتفه وساعات عمله. حي جمهوريت، شارع سلطان ألب أرسلان، رقم 2/1، أرديشن / ريزة."},
 "Adınız ve soyadınız":{"en":"Your full name","ka":"თქვენი სახელი და გვარი","ar":"اسمكم الكامل"},
 "05xx xxx xx xx": K("05xx xxx xx xx"),
 "Mesajınızı yazın":{"en":"Write your message","ka":"დაწერეთ თქვენი შეტყობინება","ar":"اكتبوا رسالتكم"},
 "Kampanyalar ve İndirimler — Park":{"en":"Campaigns and Discounts — Park Ardeşen AVM | Ardeşen","ka":"აქციები და ფასდაკლებები — Park Ardeşen AVM | არდეშენი","ar":"العروض والخصومات — بارك أرديشن مول | أرديشن"},
 "Park Ardeşen AVM mağazalarındaki güncel kampanyalar":{"en":"Current campaigns, discounts and offers at the stores of Park Ardeşen AVM: LC Waikiki, FLO, Migros, Madame Coco and more.","ka":"მიმდინარე აქციები, ფასდაკლებები და შეთავაზებები Park Ardeşen AVM-ის მაღაზიებში: LC Waikiki, FLO, Migros, Madame Coco და სხვა.","ar":"العروض والخصومات الحالية في متاجر بارك أرديشن مول: LC Waikiki و FLO و Migros و Madame Coco وغيرها."},
 "Duyurular — Park Ardeşen AVM":{"en":"Announcements — Park Ardeşen AVM | Ardeşen, Rize","ka":"განცხადებები — Park Ardeşen AVM | არდეშენი, რიზე","ar":"الإعلانات — بارك أرديشن مول | أرديشن، ريزة"},
 "Basında Biz":{"en":"In the Press","ka":"პრესაში ჩვენ შესახებ","ar":"نحن في الصحافة"},
 "Duyurular yükleniyor…":{"en":"Loading announcements…","ka":"განცხადებები იტვირთება…","ar":"جارٍ تحميل الإعلانات…"},
 "Çalışma saati değişiklikleri, yeni mağaza":{"en":"Changes to opening hours, new store openings, events and prize draws at Park Ardeşen AVM.","ka":"სამუშაო საათების ცვლილებები, ახალი მაღაზიების გახსნა, ღონისძიებები და გათამაშებები Park Ardeşen AVM-ში.","ar":"تغييرات ساعات العمل وافتتاح متاجر جديدة والفعاليات والسحوبات في بارك أرديشن مول."},
 "Sıkça Sorulan Sorular — Park":{"en":"Frequently Asked Questions — Park Ardeşen AVM | Ardeşen, Rize","ka":"ხშირად დასმული კითხვები — Park Ardeşen AVM | არდეშენი, რიზე","ar":"الأسئلة الشائعة — بارك أرديشن مول | أرديشن، ريزة"},
 "Park Ardeşen AVM nerede?":{"en":"Where is Park Ardeşen AVM?","ka":"სად მდებარეობს Park Ardeşen AVM?","ar":"أين يقع بارك أرديشن مول؟"},
 "Merkezimiz Rize'nin Ardeşen ilçesinde":{"en":"Our centre is in the Ardeşen district of Rize, at Cumhuriyet Mahallesi Sultan Alparslan Caddesi No: 2/1.","ka":"ჩვენი ცენტრი მდებარეობს რიზეს არდეშენის რაიონში, მისამართზე Cumhuriyet Mahallesi Sultan Alparslan Caddesi No: 2/1.","ar":"يقع مركزنا في قضاء أرديشن بولاية ريزة، في حي جمهوريت، شارع سلطان ألب أرسلان، رقم 2/1."},
 "Çalışma saatleriniz nedir?":{"en":"What are your opening hours?","ka":"როგორია თქვენი სამუშაო საათები?","ar":"ما هي ساعات عملكم؟"},
 "Haftanın yedi günü 10:00":{"en":"We are open seven days a week from 10:00 to 22:00. Hours may change during Ramadan, religious holidays and special days.","ka":"ღიად ვართ კვირაში შვიდივე დღე 10:00-დან 22:00-მდე. საათები შესაძლოა შეიცვალოს რამადანის, დღესასწაულებისა და განსაკუთრებული დღეების დროს.","ar":"نفتح سبعة أيام في الأسبوع من الساعة 10:00 حتى 22:00. وقد تتغيّر الساعات في شهر رمضان والأعياد والمناسبات الخاصة."},
 "Otopark var mı?":{"en":"Is there parking?","ka":"არის პარკინგი?","ar":"هل يوجد موقف سيارات؟"},
 "Evet. Ziyaretçilerimiz için ücretsiz":{"en":"Yes. Free parking is available for our visitors.","ka":"დიახ. ჩვენი სტუმრებისთვის ხელმისაწვდომია უფასო პარკინგი.","ar":"نعم. يتوفّر موقف مجاني لزوّارنا."},
 "Merkezde kaç mağaza var?":{"en":"How many stores are there in the centre?","ka":"რამდენი მაღაზიაა ცენტრში?","ar":"كم متجرًا في المركز؟"},
 "Üç kata yayılan 17 mağaza, kafe":{"en":"There are 17 stores, cafés and entertainment spots across three floors. You can see the current list on the Stores page.","ka":"სამ სართულზეა განთავსებული 17 მაღაზია, კაფე და გასართობი ადგილი. მიმდინარე ჩამონათვალი იხილეთ მაღაზიების გვერდზე.","ar":"يضمّ المركز 17 متجرًا ومقهى ومكانًا ترفيهيًا موزّعة على ثلاثة طوابق. ويمكنكم الاطّلاع على القائمة الحالية في صفحة المتاجر."},
 "Hangi markalar var?":{"en":"Which brands are there?","ka":"რომელი ბრენდებია?","ar":"ما هي العلامات التجارية الموجودة؟"},
 "LC Waikiki, Migros, FLO, Madame Coco, Bargello, Long Street":{"en":"LC Waikiki, Migros, FLO, Madame Coco, Bargello, Long Street, Paul & Mark and Lux are among our main stores. On the dining floor you will find Burger King, Popeyes, Gloria Jean's Coffees and more.","ka":"LC Waikiki, Migros, FLO, Madame Coco, Bargello, Long Street, Paul & Mark და Lux ჩვენი მთავარი მაღაზიებია. კვების ზონაში იხილავთ Burger King-ს, Popeyes-ს, Gloria Jean's Coffees-ს და სხვას.","ar":"من أبرز متاجرنا LC Waikiki و Migros و FLO و Madame Coco و Bargello و Long Street و Paul & Mark و Lux. وفي طابق المطاعم تجدون Burger King و Popeyes و Gloria Jean's Coffees وغيرها."},
 "Çocuklar için oyun alanı var mı?":{"en":"Is there a play area for children?","ka":"არის საბავშვო სათამაშო ზონა?","ar":"هل توجد منطقة ألعاب للأطفال؟"},
 "Evet. İkinci katta Berru Park":{"en":"Yes. The Berru Park play area and the Grand Bowling alley are on the second floor.","ka":"დიახ. მეორე სართულზეა Berru Park-ის სათამაშო ზონა და Grand Bowling-ის დარბაზი.","ar":"نعم. تقع منطقة ألعاب Berru Park وصالة Grand Bowling في الطابق الثاني."},
 "Mescit ve bebek bakım odası var mı?":{"en":"Are there a prayer room and a baby care room?","ka":"არის სამლოცველო და ბავშვის მოვლის ოთახი?","ar":"هل يوجد مصلّى وغرفة للعناية بالطفل؟"},
 "Her ikisi de mevcut":{"en":"Both are available. There is also a first aid room, an accessible toilet, strollers and phone charging points.","ka":"ორივე ხელმისაწვდომია. ასევე არის პირველადი დახმარების ოთახი, ადაპტირებული საპირფარეშო, საბავშვო ეტლები და ტელეფონის დამტენი წერტილები.","ar":"كلاهما متوفّر. كما توجد غرفة إسعافات أولية ودورة مياه لذوي الاحتياجات وعربات أطفال ونقاط لشحن الهواتف."},
 "İade ve değişim nasıl yapılıyor?":{"en":"How do returns and exchanges work?","ka":"როგორ ხდება დაბრუნება და გაცვლა?","ar":"كيف تتمّ عمليات الإرجاع والاستبدال؟"},
 "İade ve değişim koşulları":{"en":"Return and exchange conditions are subject to each store's own policy. Park Ardeşen AVM does not intervene in the terms applied by the stores.","ka":"დაბრუნებისა და გაცვლის პირობები ექვემდებარება თითოეული მაღაზიის საკუთარ პოლიტიკას. Park Ardeşen AVM არ ერევა მაღაზიების მიერ დადგენილ პირობებში.","ar":"تخضع شروط الإرجاع والاستبدال لسياسة كل متجر على حدة. ولا يتدخّل بارك أرديشن مول في الشروط التي تطبّقها المتاجر."},
 "Ücretsiz Wi-Fi var mı?":{"en":"Is there free Wi-Fi?","ka":"არის უფასო Wi-Fi?","ar":"هل تتوفّر شبكة Wi-Fi مجانية؟"},
 "Evet, merkez genelinde ücretsiz":{"en":"Yes, free Wi-Fi is available throughout the centre.","ka":"დიახ, უფასო Wi-Fi ხელმისაწვდომია მთელ ცენტრში.","ar":"نعم، تتوفّر شبكة Wi-Fi مجانية في أنحاء المركز."},
 "Mağaza kiralamak istiyorum":{"en":"I would like to lease a store — who should I contact?","ka":"მინდა მაღაზიის დაქირავება — ვის დავუკავშირდე?","ar":"أرغب في استئجار متجر — بمن أتواصل؟"},
 "Mağaza, kiosk ve reklam alanı talepleriniz":{"en":"For store, kiosk and advertising space enquiries you can reach our leasing team on 0464 715 30 30 or at","ka":"მაღაზიის, კიოსკისა და სარეკლამო ფართის შესახებ დაუკავშირდით ჩვენს საიჯარო გუნდს ნომერზე 0464 715 30 30 ან მისამართზე","ar":"للاستفسار عن المتاجر والأكشاك والمساحات الإعلانية يمكنكم التواصل مع فريق التأجير على 0464 715 30 30 أو عبر"},
})
