import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ekle import ekle
ekle({
 "haklarına sahipsiniz.":{"en":"You hold these rights.","ka":"თქვენ გაქვთ ეს უფლებები.","ar":"لكم هذه الحقوق."},
 "içinde sonuçlandırılır.":{"en":"at the latest.","ka":"არაუგვიანეს ამ ვადისა.","ar":"كحدّ أقصى."},
 "9. Değişiklikler":{"en":"9. Changes","ka":"9. ცვლილებები","ar":"9. التعديلات"},
 "Bu metin gerektiğinde güncellenir":{"en":"This text is updated as needed; the current version is always published on this page.","ka":"ეს ტექსტი საჭიროებისამებრ ახლდება; მიმდინარე ვერსია ყოველთვის ამ გვერდზეა გამოქვეყნებული.","ar":"يُحدَّث هذا النص عند الحاجة؛ وتُنشر النسخة الحالية دائمًا على هذه الصفحة."},
 "Park Ardeşen AVM internet sitesinde kişisel":{"en":"Information on the processing of personal data, use of cookies and your rights under KVKK on the Park Ardeşen AVM website.","ka":"ინფორმაცია პერსონალურ მონაცემთა დამუშავების, ქუქი-ფაილების გამოყენებისა და KVKK-ით გათვალისწინებული უფლებების შესახებ Park Ardeşen AVM-ის ვებგვერდზე.","ar":"معلومات عن معالجة البيانات الشخصية واستخدام ملفات الارتباط وحقوقكم بموجب KVKK في موقع بارك أرديشن مول."},
 "Park Ardeşen AVM — Ardeşen'in Alışveriş":{"en":"Park Ardeşen AVM — Ardeşen's Shopping and Lifestyle Centre | Rize","ka":"Park Ardeşen AVM — არდეშენის სავაჭრო და გასართობი ცენტრი | რიზე","ar":"بارك أرديشن مول — مركز التسوّق والحياة في أرديشن | ريزة"},
 "Ardeşen'in kalbinde":{"en":"In the heart of Ardeşen","ka":"არდეშენის გულში","ar":"في قلب أرديشن"},
 "alışverişin yeni adresi":{"en":"the new address for shopping","ka":"შოპინგის ახალი მისამართი","ar":"العنوان الجديد للتسوّق"},
 "Alışveriş":{"en":"Shopping","ka":"შოპინგი","ar":"تسوّق"},
 "ve keyif":{"en":"and pleasure","ka":"და სიამოვნება","ar":"ومتعة"},
 "bir arada":{"en":"together","ka":"ერთად","ar":"معًا"},
 "Moda, market, yeme-içme ve eğlence":{"en":"Fashion, groceries, dining and entertainment — your favourite brands under one roof.","ka":"მოდა, სასურსათო, კვება და გართობა — თქვენი საყვარელი ბრენდები ერთ სივრცეში.","ar":"أزياء وبقالة ومطاعم وترفيه — علاماتكم المفضّلة تحت سقف واحد."},
 "Markaları keşfet":{"en":"Discover the brands","ka":"აღმოაჩინეთ ბრენდები","ar":"اكتشفوا العلامات"},
 "İçeride":{"en":"What's","ka":"რა არის","ar":"ماذا"},
 "neler var":{"en":"inside","ka":"შიგნით","ar":"يوجد بالداخل"},
 "Park Ardeşen AVM'de 17 mağaza, kafe":{"en":"17 stores, cafés and entertainment spots await you at Park Ardeşen AVM.","ka":"Park Ardeşen AVM-ში გელოდებათ 17 მაღაზია, კაფე და გასართობი ადგილი.","ar":"ينتظركم 17 متجرًا ومقهى ومكانًا ترفيهيًا في بارك أرديشن مول."},
 "Mağazaları gör":{"en":"See the stores","ka":"იხილეთ მაღაზიები","ar":"استعرضوا المتاجر"},
 "Moda & Giyim":{"en":"Fashion & Clothing","ka":"მოდა და ტანსაცმელი","ar":"الأزياء والملابس"},
 "Ayakkabı & Çanta":{"en":"Shoes & Bags","ka":"ფეხსაცმელი და ჩანთები","ar":"الأحذية والحقائب"},
 "Yeme & İçme":{"en":"Food & Drink","ka":"კვება და სასმელი","ar":"المأكولات والمشروبات"},
 "Kozmetik & Parfüm":{"en":"Cosmetics & Perfume","ka":"კოსმეტიკა და პარფიუმერია","ar":"مستحضرات التجميل والعطور"},
 "Eğlence & Çocuk":{"en":"Entertainment & Kids","ka":"გართობა და ბავშვები","ar":"الترفيه والأطفال"},
 "Ev & Yaşam":{"en":"Home & Living","ka":"სახლი და ცხოვრება","ar":"المنزل والمعيشة"},
 "Market":{"en":"Supermarket","ka":"სუპერმარკეტი","ar":"سوبر ماركت"},
 "Ailenizle":{"en":"An enjoyable","ka":"სასიამოვნო","ar":"يوم ممتع"},
 "keyifli bir":{"en":"day with","ka":"დღე თქვენს","ar":"مع"},
 "gün":{"en":"your family","ka":"ოჯახთან ერთად","ar":"عائلتكم"},
 "Park Ardeşen’den":{"en":"News from","ka":"სიახლეები","ar":"إعلانات"},
 "duyurular":{"en":"Park Ardeşen","ka":"Park Ardeşen-იდან","ar":"من بارك أرديشن"},
 "Çalışma saatleri, yeni açılışlar":{"en":"Up-to-date information on opening hours, new openings and events.","ka":"განახლებული ინფორმაცია სამუშაო საათების, ახალი გახსნებისა და ღონისძიებების შესახებ.","ar":"معلومات محدَّثة عن ساعات العمل والافتتاحات الجديدة والفعاليات."},
 "Tüm duyurular":{"en":"All announcements","ka":"ყველა განცხადება","ar":"جميع الإعلانات"},
 "kampanya":{"en":"campaign","ka":"აქციის","ar":"عروض"},
 "fırsatları":{"en":"offers","ka":"შეთავაზებები","ar":"وخصومات"},
 "Mağazalarımızdaki güncel indirim":{"en":"All the current discounts and offers at our stores are here.","ka":"ჩვენს მაღაზიებში მიმდინარე ყველა ფასდაკლება და შეთავაზება აქაა.","ar":"جميع الخصومات والعروض الحالية في متاجرنا هنا."},
 "Tüm kampanyalar":{"en":"All campaigns","ka":"ყველა აქცია","ar":"جميع العروض"},
 "Kat planını":{"en":"Explore the","ka":"გაეცანით","ar":"استكشفوا"},
 "keşfet":{"en":"floor plan","ka":"სართულის გეგმას","ar":"مخطط الطوابق"},
 "Ziyaretinizi kolayca planlayın":{"en":"Plan your visit easily: use the floor plan to go straight to the store you are looking for.","ka":"დაგეგმეთ ვიზიტი მარტივად: სართულის გეგმით პირდაპირ მიაღწიეთ სასურველ მაღაზიას.","ar":"خطّطوا لزيارتكم بسهولة: استخدموا مخطط الطوابق للوصول مباشرة إلى المتجر الذي تبحثون عنه."},
 "Kat planına bak":{"en":"View the floor plan","ka":"იხილეთ სართულის გეგმა","ar":"عرض مخطط الطوابق"},
 "Takip et":{"en":"Follow","ka":"გამოგვყევით","ar":"تابعونا"},
 "Rize Ardeşen'de LC Waikiki, Migros":{"en":"LC Waikiki, Migros, FLO, Madame Coco and more in Ardeşen, Rize. Dining floor, children's play area, bowling and free parking.","ka":"LC Waikiki, Migros, FLO, Madame Coco და სხვა არდეშენში, რიზე. კვების ზონა, საბავშვო სათამაშო ადგილი, ბოულინგი და უფასო პარკინგი.","ar":"LC Waikiki و Migros و FLO و Madame Coco وغيرها في أرديشن، ريزة. طابق مطاعم ومنطقة ألعاب للأطفال وبولينغ وموقف مجاني."},
 "Bu internet sitesini kullanarak":{"en":"By using this website you accept the following terms.","ka":"ამ ვებგვერდის გამოყენებით თქვენ ეთანხმებით ქვემოთ მოცემულ პირობებს.","ar":"باستخدامكم هذا الموقع فإنكم توافقون على الشروط التالية."},
 "Sitenin kullanımı":{"en":"Use of the site","ka":"საიტის გამოყენება","ar":"استخدام الموقع"},
 "Site, Park Ardeşen Alışveriş ve Yaşam Merkezi hakkında":{"en":"The site is published to provide information about Park Ardeşen Shopping and Lifestyle Centre. No sales are made through it.","ka":"საიტი გამოქვეყნებულია Park Ardeşen — სავაჭრო და გასართობი ცენტრის შესახებ ინფორმაციის მისაწოდებლად. მისი მეშვეობით გაყიდვები არ ხორციელდება.","ar":"يُنشر الموقع لتقديم معلومات عن بارك أرديشن — مركز التسوّق والحياة. ولا تُجرى عبره أي عمليات بيع."},
 "İçeriğin doğruluğu":{"en":"Accuracy of content","ka":"შიგთავსის სიზუსტე","ar":"دقة المحتوى"},
 "Mağaza listesi, kat yerleşimi":{"en":"The store list, floor layout, opening hours and campaign information may change. We make every effort to keep the information current, but no guarantee is given that it is complete and error-free at all times.","ka":"მაღაზიების ჩამონათვალი, სართულების განლაგება, სამუშაო საათები და აქციების ინფორმაცია შეიძლება შეიცვალოს. ვცდილობთ ინფორმაცია განახლებული იყოს, თუმცა არ იძლევა გარანტიას, რომ ის ყოველთვის სრული და უშეცდომოა.","ar":"قد تتغيّر قائمة المتاجر وتوزيع الطوابق وساعات العمل ومعلومات العروض. ونبذل ما بوسعنا لإبقاء المعلومات محدَّثة، لكن لا نضمن أنها كاملة وخالية من الأخطاء في كل وقت."},
 "Kampanyalar ve mağaza uygulamaları":{"en":"Campaigns and store practices","ka":"აქციები და მაღაზიების პრაქტიკა","ar":"العروض وممارسات المتاجر"},
 "Sitede yer alan kampanyalar ilgili":{"en":"The campaigns shown on the site are run by the relevant stores. Discount rates, stock availability and conditions are determined by the stores.","ka":"საიტზე მოცემულ აქციებს ახორციელებენ შესაბამისი მაღაზიები. ფასდაკლების პროცენტი, მარაგი და პირობები განისაზღვრება მაღაზიების მიერ.","ar":"تُدار العروض المعروضة في الموقع من قِبل المتاجر المعنية. وتحدّد المتاجر نسب الخصم وتوافر المخزون والشروط."},
 "Fikri mülkiyet":{"en":"Intellectual property","ka":"ინტელექტუალური საკუთრება","ar":"الملكية الفكرية"},
 "Sitede yer alan metin, görsel ve logolar":{"en":"The texts, images and logos on the site belong to their respective rights holders. Store logos are used only for identification purposes.","ka":"საიტზე განთავსებული ტექსტები, სურათები და ლოგოები ეკუთვნის შესაბამის უფლების მფლობელებს. მაღაზიების ლოგოები გამოიყენება მხოლოდ საიდენტიფიკაციო მიზნით.","ar":"النصوص والصور والشعارات في الموقع مملوكة لأصحاب الحقوق المعنيين. وتُستخدم شعارات المتاجر لأغراض التعريف فقط."},
 "Dış bağlantılar":{"en":"External links","ka":"გარე ბმულები","ar":"الروابط الخارجية"},
 "Site, üçüncü taraflara ait adreslere":{"en":"The site may link to third-party addresses. Park Ardeşen AVM is not responsible for the content of those addresses.","ka":"საიტს შეიძლება ჰქონდეს ბმულები მესამე მხარის მისამართებზე. Park Ardeşen AVM არ აგებს პასუხს ამ მისამართების შიგთავსზე.","ar":"قد يتضمّن الموقع روابط إلى عناوين تخصّ أطرافًا ثالثة. ولا يتحمّل بارك أرديشن مول مسؤولية محتوى تلك العناوين."},
 "Değişiklik hakkı":{"en":"Right to make changes","ka":"ცვლილების უფლება","ar":"حق التعديل"},
 "Bu koşullar önceden haber verilmeksizin":{"en":"These terms may be updated without prior notice. The current text is always published on this page.","ka":"ეს პირობები შესაძლოა განახლდეს წინასწარი შეტყობინების გარეშე. მიმდინარე ტექსტი ყოველთვის ამ გვერდზეა.","ar":"قد تُحدَّث هذه الشروط دون إشعار مسبق. ويُنشر النص الحالي دائمًا على هذه الصفحة."},
 "Mağaza Kiralama — Park":{"en":"Store Leasing — Park Ardeşen AVM | Ardeşen, Rize","ka":"მაღაზიის იჯარა — Park Ardeşen AVM | არდეშენი, რიზე","ar":"تأجير المتاجر — بارك أرديشن مول | أرديشن، ريزة"},
 "Park Ardeşen AVM'de yerinizi alın":{"en":"Take your place at Park Ardeşen AVM","ka":"დაიკავეთ ადგილი Park Ardeşen AVM-ში","ar":"احجزوا مكانكم في بارك أرديشن مول"},
 "Park Ardeşen AVM, Ardeşen'in en yoğun caddesinde;":{"en":"Park Ardeşen AVM stands on Ardeşen's busiest street, at the meeting point of local residents, nearby towns and visitors to the region.","ka":"Park Ardeşen AVM მდებარეობს არდეშენის ყველაზე მოძრავ ქუჩაზე, ადგილობრივების, მეზობელი დაბებისა და რეგიონის სტუმრების შეხვედრის წერტილში.","ar":"يقع بارك أرديشن مول في أكثر شوارع أرديشن ازدحامًا، عند نقطة التقاء السكان المحليين والبلدات المجاورة وزوّار المنطقة."},
 "Moda, ayakkabı, ev tekstili, kozmetik, elektronik":{"en":"Units of various sizes are available in the fashion, footwear, home textiles, cosmetics, electronics and food and drink categories.","ka":"სხვადასხვა ფართობის ერთეულები ხელმისაწვდომია მოდის, ფეხსაცმლის, საოჯახო ტექსტილის, კოსმეტიკის, ელექტრონიკისა და კვების კატეგორიებში.","ar":"تتوفّر وحدات بمساحات مختلفة في فئات الأزياء والأحذية ومفروشات المنزل ومستحضرات التجميل والإلكترونيات والمأكولات والمشروبات."},
 "Kiosk, stant ve reklam alanları":{"en":"Kiosks, stands and advertising spaces","ka":"კიოსკები, სტენდები და სარეკლამო ფართები","ar":"الأكشاك والمنصّات والمساحات الإعلانية"},
 "Kısa süreli tanıtım standı, kiosk, araç teşhiri, dijital ekran ve ATM yerleşimi gibi esnek":{"en":"Flexible options are available such as short-term promotion stands, kiosks, vehicle displays, digital screens and ATM placements.","ka":"ხელმისაწვდომია მოქნილი ვარიანტები: მოკლევადიანი სარეკლამო სტენდები, კიოსკები, ავტომობილის ექსპოზიცია, ციფრული ეკრანები და ბანკომატის განთავსება.","ar":"تتوفّر خيارات مرنة مثل منصّات الترويج قصيرة الأمد والأكشاك وعرض المركبات والشاشات الرقمية وتركيب أجهزة الصرّاف الآلي."},
 "Güncel boş birimler":{"en":"Currently available units","ka":"ამჟამად თავისუფალი ერთეულები","ar":"الوحدات المتاحة حاليًا"},
 "Birim listesi yükleniyor…":{"en":"Loading unit list…","ka":"ერთეულების სია იტვირთება…","ar":"جارٍ تحميل قائمة الوحدات…"},
 "Adres: Cumhuriyet Mah.":{"en":"Address: Cumhuriyet Mah. Sultan Alparslan Cad. No: 2/1, 53400 Ardeşen / Rize","ka":"მისამართი: Cumhuriyet Mah. Sultan Alparslan Cad. No: 2/1, 53400 არდეშენი / რიზე","ar":"العنوان: حي جمهوريت، شارع سلطان ألب أرسلان، رقم 2/1، 53400 أرديشن / ريزة"},
 "Ardeşen'in en işlek noktasında":{"en":"At Ardeşen's busiest spot, with street-facing and upper-floor units, we offer space to suit your brand.","ka":"არდეშენის ყველაზე მოძრავ ადგილას, ქუჩის ფასადისა და ზედა სართულის ერთეულებით, გთავაზობთ თქვენს ბრენდზე მორგებულ ფართს.","ar":"في أكثر مواقع أرديشن حركة، وبوحدات مطلّة على الشارع وأخرى في الطوابق العليا، نوفّر مساحة تناسب علامتكم."},
 "Merkezimiz ilçe sakinlerinin yanı sıra":{"en":"Besides local residents, our centre also welcomes visitors travelling on the Fındıklı, Pazar, Çamlıhemşin and Ayder routes.","ka":"ადგილობრივების გარდა, ჩვენი ცენტრი მასპინძლობს ფინდიკლის, ფაზარის, ჩამლიჰემშინისა და აიდერის მიმართულების სტუმრებსაც.","ar":"إلى جانب السكان المحليين، يستقبل مركزنا أيضًا الزوّار القادمين عبر طرق فيندكلي وبازار وتشامليهمشين وآيدر."},
 "Kiralama başvurusu":{"en":"Leasing application","ka":"საიჯარო განაცხადი","ar":"طلب التأجير"},
 "Kiosk ve reklam alanları":{"en":"Kiosks and advertising spaces","ka":"კიოსკები და სარეკლამო ფართები","ar":"الأكشاك والمساحات الإعلانية"},
 "Kısa süreli kullanım için kiosk":{"en":"Kiosks, promotion stands, vehicle display areas, digital screens and ATM placements are available for short-term use.","ka":"მოკლევადიანი გამოყენებისთვის ხელმისაწვდომია კიოსკები, სარეკლამო სტენდები, ავტომობილის საექსპოზიციო ადგილები, ციფრული ეკრანები და ბანკომატის განთავსება.","ar":"تتوفّر للاستخدام قصير الأمد أكشاك ومنصّات ترويج ومساحات لعرض المركبات وشاشات رقمية وأماكن لأجهزة الصرّاف الآلي."},
 "Sezonluk kampanya, lansman ve etkinlik":{"en":"For seasonal campaigns, launches and event space needs, our team will put together a tailored solution with you.","ka":"სეზონური აქციების, პრეზენტაციებისა და ღონისძიების სივრცის საჭიროებისთვის ჩვენი გუნდი თქვენთან ერთად შეიმუშავებს ინდივიდუალურ გადაწყვეტას.","ar":"ولاحتياجات العروض الموسمية وإطلاق المنتجات ومساحات الفعاليات، يضع فريقنا معكم حلاً مخصّصًا."},
 "KİRALAMA İLETİŞİM":{"en":"LEASING CONTACT","ka":"საიჯარო კონტაქტი","ar":"جهة اتصال التأجير"},
})
